title: TTS Engineering Practices Guide

styles:
  - /assets/css/styles.css

exclude:
  - vendor
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - go
  - copy-template

theme: uswds-jekyll

url: "https://engineering.18f.gov"
plugins:
  - jekyll-sitemap

include:
  - .rubocop.yml # in _pages/ruby

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown

sass:
  style: compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

google_analytics_ua: UA-48605964-19

repo:
  name: TTS Engineering Practices Guide
  description: Main repository
  url: https://github.com/18F/development-guide

back_link:
  url: "https://18f.gsa.gov/guides/"
  text: Read more 18F Guides
