baseurl: /frontend
markdown: redcarpet
name: Frontend Guides
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

defaults:
-
  scope:
    path: "pages"
  values:
    layout: "default"
    edit_info:
      repo: 18F/frontend
      branch: master

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: CSS Coding Styleguide
  url: css-coding-styleguide/
  internal: true
  children: 
  - text: Preprocessor
    url: preprocessor/
    internal: true
  - text: Frameworks
    url: frameworks/
    internal: true
  - text: Format
    url: format/
    internal: true
  - text: Units
    url: units/
    internal: true
  - text: Naming
    url: naming/
    internal: true
  - text: Inheritance
    url: inheritance/
    internal: true 
  - text: Architecture
    url: architecture/
    internal: true 
  - text: Specificity
    url: specificity/
    internal: true 
  - text: Variables
    url: variables/
    internal: true
  - text: Documentation
    url: documentation/
    internal: true                                 
- text: Web Components
  url: web-components/
  internal: true

repos:
- name: Frontend Guides
  description: Main repository
  url: https://github.com/18F/guides-template

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: UA-48605964-19
