title: 18F Front End Guide

permalink: pretty
highlighter: rouge
markdown: redcarpet

redcarpet:
  extensions: ['tables']

sass:
  style: compressed

exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - go

collections:
  - chapters

include:
  - .scss-lint.yml

google_analytics_ua: UA-48605964-19

author:
 name: 18F
 url: https://18f.gsa.gov

repos:
  - name: Front End Guide
    description: Main repository
    url: https://github.com/18F/frontend

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides
