title: 18F Front End Guide

styles:
  - /assets/css/styles.css

exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - go

theme: uswds-jekyll

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

permalink: pretty
markdown: kramdown

sass:
  style: compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

google_analytics_ua: UA-48605964-19

repo:
  name: Front End Guide
  description: Main repository
  url: https://github.com/18F/frontend

back_link:
  url: "https://guides.18f.gov/"
  text: Read more 18F Guides
