# Configuration in this file overrides those in _config.yml.
# Required keys:
# - title
# - description
# - url
# - github_info
# - search_site_handle
# Optional keys
# - org

title: TTS Engineering Practices Guide
description: A set of guidelines and best practices for an awesome engineering team
url: "https://engineering.18f.gov"

# GitHub information
github_info:
  organization: 18F
  repository: development-guide
  default_branch: main

# Unique identifier across GSA for this website; the repository name is
# usually a good site handle.
search_site_handle: engineering.18f.gov

# Either 18F, Solutions, CoE, PIF, or unset to default to just TTS
org:
